language: php

php:
  - 7.0

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database churchtool;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.travis.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
